[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  checkExternal = true

[[headers]]
  for = "/protected/*"
  [headers.values]
    Basic-Auth = "rstav:yomama"

  [[headers]]
  for = "/secret/*"
  [headers.values]
    Basic-Auth = "rstav:mamayo"