name: Docs UI feature request
description: Suggest a feature request to add to or update the UI for the external-facing docs site. (Not content-related)
title: "Add your feature request title here"
labels: ['site enhancement','needs frontend']
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a new feature or improvement for the docs site!
  - type: textarea
    attributes:
      label: What problem or opportunity does this feature request address?
      placeholder: A clear and concise description of what the problem or opportunity is. If applicable, add screenshots or a link to a video recording to help explain.
  - type: textarea
    attributes:
      label: Describe the solution
      placeholder: |
        This could be addressed by [...]
  - type: textarea
    attributes:
      label: Alternatives you've considered
      placeholder: Any alternative solutions or features you've considered
  - type: textarea
    attributes:
      label: Additional context
      placeholder: |
        If needed, add any other context about the feature request
  - type: markdown
    attributes:
      value: |
        ---
        ## Next steps
          1. This issue will be automatically added to the Triage column of the [Writing Task Board](https://github.com/orgs/netlify/projects/229) using a GitHub Action.
          2. The Docs team will triage the issue at a weekly triage meeting. For questions, reach out to us in the #crew-docs Slack channel or comment on this issue.