name: Style guide
description: Add or update a style guide entry.
labels: ["docs: styleguide"]
title: "Add your title here"
body:
  - type: markdown
    attributes:
      value: |
        Use this issue template to track updates and additions to the [Netlify Style Guide](https://netlify-handbook.netlify.app/product/documentation/docs-style-guide).
  - type: dropdown
    attributes:
      label: What kind of work is needed for an entry or style guide section?
      multiple: true
      options:
        - Add
        - Update
  - type: textarea
    attributes:
      label: Describe the updates or additions
      description: 
      placeholder:  |
        A description of what needs to be updated or added to the style guide
  - type: textarea
    attributes:
      label: Stakeholders
      placeholder: |
        People who may need to be informed or consulted for this work
  - type: textarea
    attributes:
      label: Timeline
      placeholder: Add a timeline if it's relevant
  - type: textarea
    attributes:
      label: Additional context
      placeholder: |
        If needed, add any other context about this style guide update or addition: related issues, forum posts, support tickets, Notion links, screenshots, or other supporting information about the request
  - type: markdown
    attributes:
      value: |
        ---
        ## Next steps
          1. This issue will be automatically added to the Triage column of the [Writing Task Board](https://github.com/orgs/netlify/projects/229) using a GitHub Action.
          2. The Docs team will triage the issue at a weekly triage meeting. For questions, reach out to us in the [#crew-docs Slack channel](https://netlify.slack.com/archives/C6NVA4FS6) or comment on this issue.