name: Test Report
description: File a test report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this test report!
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.